spring:
  application:
    name: stock-crawling-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stock_db
    username: pjh1997
    password: parkjh123!@#

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql
